"""add integration plan to agent runs

Revision ID: 33399bd7860f
Revises: 93e9b31d40e1
Create Date: 2026-09-03 10:16:38.272147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33399bd7860f'
down_revision: Union[str, Sequence[str], None] = '93e9b31d40e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('integration_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'integration_plan')
    # ### end Alembic commands ###
