"""add github document identity

Revision ID: da8d071e2b5d
Revises: 930e2716c138
Create Date: 2026-08-24 22:47:23.621575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8d071e2b5d'
down_revision: Union[str, Sequence[str], None] = '930e2716c138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('github_path', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('github_sha', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_documents_github_path'), 'documents', ['github_path'], unique=False)
    op.create_index(op.f('ix_documents_github_sha'), 'documents', ['github_sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_github_sha'), table_name='documents')
    op.drop_index(op.f('ix_documents_github_path'), table_name='documents')
    op.drop_column('documents', 'github_sha')
    op.drop_column('documents', 'github_path')
    # ### end Alembic commands ###
