from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.services.github_service import GitHubService


@pytest.mark.asyncio
async def test_create_branch():
    service = GitHubService()

    source_ref = {
        "ref": "refs/heads/main",
        "object": {
            "sha": "source-sha-123",
        },
    }

    service.get_branch = AsyncMock(
        return_value=source_ref
    )

    service._post_installation = AsyncMock(
        return_value={
            "ref": "refs/heads/agent/test-branch",
        }
    )

    result = await service.create_branch(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        branch_name="agent/test-branch",
        source_branch="main",
    )

    assert result["ref"] == "refs/heads/agent/test-branch"

    service.get_branch.assert_awaited_once_with(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        branch="main",
    )

    service._post_installation.assert_awaited_once_with(
        "/repos/acme/payments-api/git/refs",
        "installation-token",
        json={
            "ref": "refs/heads/agent/test-branch",
            "sha": "source-sha-123",
        },
    )


@pytest.mark.asyncio
async def test_create_or_update_file():
    service = GitHubService()

    service._put_installation = AsyncMock(
        return_value={
            "content": {
                "path": "src/payment.py",
                "sha": "new-sha",
            }
        }
    )

    result = await service.create_or_update_file(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        path="src/payment.py",
        content="def pay():\n    return True\n",
        branch="agent/stripe-integration",
        message="feat: integrate stripe",
        sha="existing-sha",
    )

    assert result["content"]["sha"] == "new-sha"

    service._put_installation.assert_awaited_once()

    call = service._put_installation.await_args

    assert call.args[0] == (
        "/repos/acme/payments-api/contents/src/payment.py"
    )

    assert call.args[1] == "installation-token"

    payload = call.kwargs["json"]

    assert payload["message"] == "feat: integrate stripe"
    assert payload["branch"] == "agent/stripe-integration"
    assert payload["sha"] == "existing-sha"

    # Verify the content was base64 encoded.
    import base64

    decoded = base64.b64decode(
        payload["content"]
    ).decode("utf-8")

    assert decoded == "def pay():\n    return True\n"


@pytest.mark.asyncio
async def test_create_new_file_without_sha():
    service = GitHubService()

    service._put_installation = AsyncMock(
        return_value={
            "content": {
                "path": "src/new_file.py",
            }
        }
    )

    await service.create_or_update_file(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        path="src/new_file.py",
        content="print('hello')\n",
        branch="agent/test",
        message="feat: add new file",
    )

    payload = service._put_installation.await_args.kwargs[
        "json"
    ]

    assert "sha" not in payload


@pytest.mark.asyncio
async def test_get_file():
    service = GitHubService()

    service._get_installation = AsyncMock(
        return_value={
            "path": "src/payment.py",
            "sha": "file-sha",
            "content": "encoded-content",
        }
    )

    result = await service.get_file(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        path="src/payment.py",
        branch="agent/test",
    )

    assert result["sha"] == "file-sha"

    service._get_installation.assert_awaited_once_with(
        "/repos/acme/payments-api/contents/src/payment.py",
        "installation-token",
        params={"ref": "agent/test"},
    )


@pytest.mark.asyncio
async def test_create_pull_request():
    service = GitHubService()

    service._post_installation = AsyncMock(
        return_value={
            "number": 42,
            "html_url": (
                "https://github.com/acme/payments-api/pull/42"
            ),
        }
    )

    result = await service.create_pull_request(
        installation_token="installation-token",
        owner="acme",
        repo="payments-api",
        title="feat: integrate stripe",
        body="Generated by AI Integration Engineer.",
        head="agent/stripe-integration",
        base="main",
    )

    assert result["number"] == 42
    assert result["html_url"].endswith("/pull/42")

    service._post_installation.assert_awaited_once_with(
        "/repos/acme/payments-api/pulls",
        "installation-token",
        json={
            "title": "feat: integrate stripe",
            "body": "Generated by AI Integration Engineer.",
            "head": "agent/stripe-integration",
            "base": "main",
        },
    )
